# Generated by Django 3.2.6 on 2021-08-20 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_user_id_idea_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
