name: CI

on:
  pull_request:

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: TrueBrain/actions-flake8@master

  django:
    name: Django Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image...
        run: docker-compose build app
      - name: Executing django tests
        run: docker-compose run --rm app python manage.py test api.tests --settings=app.settings_test